/**
 * Who is anonymous on a seeded board — asked once, answered here, for everybody.
 *
 * ## The bug this exists to make impossible
 *
 * A seeded listing is anonymous. `DECISIONS.md`'s resolution of S4-source: 913 of
 * the 1028 seeded descriptions were scraped from a third-party directory rather
 * than written by the companies they describe, so a NAMED seeded row is AI
 * criticism of copy that company never wrote — the largest legal exposure in the
 * project. `products_seeded_is_anonymous` (`migrations/0009`) refuses to store the
 * alternative.
 *
 * That rule was then written down twice, in two files that do not import each
 * other: `packages/db/src/seed/build.ts` redacted every row before freezing a
 * verdict, and `apps/web/src/lib/boards/source.ts` decided the same thing again
 * for the filesystem board. Two documents, no error — the same shape as the board
 * read path that bypassed the snapshot sink, as production binding a filesystem
 * category source, and as six connection pools each documented as the only one.
 * A comment cannot bind a file that does not import it. A function can, and this
 * is the function: both origins now call it, so they cannot answer differently.
 *
 * ## Declared, not inferred
 *
 * The document may say so itself, in `anonymous_ids` — the same field a published
 * `BoardSnapshot` carries. That is preferred over any heuristic, because the
 * alternative that was there before (`url === ''`) answers a DIFFERENT question:
 * "was this row already redacted upstream", not "should this row be anonymous".
 * A seeded run's rows carry real URLs, so that sentinel called all 92 of them
 * named — which is exactly what the filesystem board published.
 *
 * ## A declaration can add, and cannot subtract
 *
 * `seededAnonymousIds` takes the UNION of what the document declares and every row
 * on it. A seeded ranking that declared a subset would not be a narrower policy,
 * it would be a corrupt document: the database refuses to store a named seeded
 * row, so a JSON file on disk is not the place someone opts one back into being
 * named. The field therefore makes the intent visible in the data — which is what
 * it is for — without being a way to weaken the rule, and a run whose file
 * predates the field (or was regenerated by `pnpm engine rank`, which writes the
 * engine's own schema and drops it) is still fully anonymous.
 */

import type { Ranking } from '@the-pit/engine';

/**
 * The field a document declares its anonymous rows in.
 *
 * The same name `BoardSnapshot.anonymous_ids` uses, deliberately: a published
 * snapshot and a seeded ranking say this in the same words, so a reader of either
 * file learns the same thing from the same key.
 */
export const ANONYMOUS_IDS_FIELD = 'anonymous_ids';

/** A ranking document that may carry the declaration. `Ranking` itself does not. */
export type RankingWithAnonymity = Ranking & { readonly [ANONYMOUS_IDS_FIELD]?: unknown };

/**
 * What a document declares, or `undefined` when it declares nothing.
 *
 * Validated rather than cast: this reads a file that this process did not write,
 * and a `null` or a string in the array must not become an engine id that matches
 * nothing. Anything that is not an array of finite numbers is treated as absent,
 * which lands the caller on the safe default rather than on a crash.
 */
export function declaredAnonymousIds(document: unknown): readonly number[] | undefined {
  if (typeof document !== 'object' || document === null) return undefined;
  const declared = (document as Record<string, unknown>)[ANONYMOUS_IDS_FIELD];
  if (!Array.isArray(declared)) return undefined;
  const ids = declared.filter((id): id is number => typeof id === 'number' && Number.isFinite(id));
  return ids.length === declared.length ? ids : undefined;
}

/**
 * Every engine id a SEEDED ranking publishes without a name or a URL.
 *
 * The union of the declaration and every row, sorted, deduplicated — see the
 * module header for why a declaration can only ever add. Both the seed builder
 * and the filesystem board read this, and `apps/web/test/anonymity-agreement.test.ts`
 * fails if either stops.
 */
export function seededAnonymousIds(ranking: RankingWithAnonymity): number[] {
  const ids = new Set<number>(ranking.ranking.map((row) => row.id));
  for (const id of declaredAnonymousIds(ranking) ?? []) ids.add(id);
  return [...ids].sort((a, b) => a - b);
}
